Repository paketo-buildpacks/azure-application-insights, pull requests merged in 2021-08, with the labels that each got.

#74 Add how to docs for java application in k8s.
  docs/how-to-use-buildpacks-in-kubernetes-for-java.md
Labels: type:documentation, semver:patch

#78 Bump libpak to 1.52.1
  .github/workflows/tests.yml
  go.mod
  go.sum
Labels: type:dependency-upgrade, semver:patch

#75 Allow Tiny stack
  buildpack.toml
Labels: type:enhancement, semver:minor
